### ISSUE TITLE
Wiew Data in Karlskrona

### ISSUE THREAD

**Issue by EdvinKristiansson** [AlexGustafsson/PA1450#1]
The customer should be able to view the weather data through a graph and selecting attributes of interest such as temperature, rainfall wind or sun hours in Karlskrona.

**Comment by AlexGustafsson** [comment]
Hi! You seem to be lost. Did you intend to create this issue in your fork over at https://github.com/EdvinKristiansson/PA1450?

Closing for now.

**Comment by EdvinKristiansson** [comment]
Ye I am trying to learn how you do it, sorry if I did something wrong I
stil have a hard time understanding the program


Den tors 7 maj 2020 kl 10:53 skrev Alex Gustafsson <notifications@github.com
